# Numpy's Random Module
https://numpy.org/doc/stable/reference/random/index.html
****


In [1]:
import numpy as np

#### PRNG Psuedo Random Number generator
Draws samples from a variety of probability distributions


In [6]:
# User creates a generator 
rng = np.random.default_rng() #Returns he initialized generator object.

print(rng)

Generator(PCG64)


In [7]:
# Generate one random float uniformly distributed over the range [0, 1)
rng.random()

0.8943532215735878

In [9]:
# Generate an array of 5 integers uniformly over the range [0, 10).
print(rng.integers(low=0, high=10, size=5))
print(type(rng.integers(low=0, high=10, size=5)))

[0 9 7 9 9]
<class 'numpy.ndarray'>


In [12]:
# Generate 10,000 integers over the range [0, 10).
x = rng.integers(low=1, high=10, size=10000, endpoint=False)
x

array([3, 7, 2, ..., 4, 7, 5], dtype=int64)

In [16]:
# Generate 1 random number in the range [0,1) with normal distribution
rng.standard_normal()

1.2801907333771831

In [15]:
# Generate an array of 10 random numbers in the range [0,1) with normal distribution
rng.standard_normal(10)

array([-0.36176244,  0.30208279,  0.09020941, -1.4140996 ,  1.42114928,
        0.88502703, -1.6502233 , -0.29873059, -1.06695261,  1.17086894])